# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='custom.proto',
  package='forge_abi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63ustom.proto\x12\tforge_abi\"Q\n\nTestTicket\x12\x0b\n\x03row\x18\x01 \x01(\t\x12\x0c\n\x04seat\x18\x02 \x01(\t\x12\x0c\n\x04room\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\tb\x06proto3')
)




_TESTTICKET = _descriptor.Descriptor(
  name='TestTicket',
  full_name='forge_abi.TestTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='forge_abi.TestTicket.row', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seat', full_name='forge_abi.TestTicket.seat', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room', full_name='forge_abi.TestTicket.room', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='forge_abi.TestTicket.time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='forge_abi.TestTicket.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['TestTicket'] = _TESTTICKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestTicket = _reflection.GeneratedProtocolMessageType('TestTicket', (_message.Message,), dict(
  DESCRIPTOR = _TESTTICKET,
  __module__ = 'custom_pb2'
  # @@protoc_insertion_point(class_scope:forge_abi.TestTicket)
  ))
_sym_db.RegisterMessage(TestTicket)


# @@protoc_insertion_point(module_scope)
