# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange_tether.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import type_pb2 as type__pb2
from . import exchange_pb2 as exchange__pb2
from . import deposit_tether_pb2 as deposit__tether__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange_tether.proto',
  package='forge_abi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x65xchange_tether.proto\x12\tforge_abi\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ntype.proto\x1a\x0e\x65xchange.proto\x1a\x14\x64\x65posit_tether.proto\"p\n\x12TetherExchangeInfo\x12!\n\x05value\x18\x01 \x01(\x0b\x32\x12.forge_abi.BigUint\x12\x0e\n\x06\x61ssets\x18\x02 \x03(\t\x12\'\n\x07\x64\x65posit\x18\x03 \x01(\x0b\x32\x16.forge_abi.Transaction\"\xc0\x01\n\x10\x45xchangeTetherTx\x12\'\n\x06sender\x18\x01 \x01(\x0b\x32\x17.forge_abi.ExchangeInfo\x12/\n\x08receiver\x18\x02 \x01(\x0b\x32\x1d.forge_abi.TetherExchangeInfo\x12.\n\nexpired_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x04\x64\x61ta\x18\x0f \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,type__pb2.DESCRIPTOR,exchange__pb2.DESCRIPTOR,deposit__tether__pb2.DESCRIPTOR,])




_TETHEREXCHANGEINFO = _descriptor.Descriptor(
  name='TetherExchangeInfo',
  full_name='forge_abi.TetherExchangeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='forge_abi.TetherExchangeInfo.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assets', full_name='forge_abi.TetherExchangeInfo.assets', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deposit', full_name='forge_abi.TetherExchangeInfo.deposit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=258,
)


_EXCHANGETETHERTX = _descriptor.Descriptor(
  name='ExchangeTetherTx',
  full_name='forge_abi.ExchangeTetherTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='forge_abi.ExchangeTetherTx.sender', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='forge_abi.ExchangeTetherTx.receiver', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expired_at', full_name='forge_abi.ExchangeTetherTx.expired_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='forge_abi.ExchangeTetherTx.data', index=3,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=453,
)

_TETHEREXCHANGEINFO.fields_by_name['value'].message_type = type__pb2._BIGUINT
_TETHEREXCHANGEINFO.fields_by_name['deposit'].message_type = type__pb2._TRANSACTION
_EXCHANGETETHERTX.fields_by_name['sender'].message_type = exchange__pb2._EXCHANGEINFO
_EXCHANGETETHERTX.fields_by_name['receiver'].message_type = _TETHEREXCHANGEINFO
_EXCHANGETETHERTX.fields_by_name['expired_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EXCHANGETETHERTX.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['TetherExchangeInfo'] = _TETHEREXCHANGEINFO
DESCRIPTOR.message_types_by_name['ExchangeTetherTx'] = _EXCHANGETETHERTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TetherExchangeInfo = _reflection.GeneratedProtocolMessageType('TetherExchangeInfo', (_message.Message,), dict(
  DESCRIPTOR = _TETHEREXCHANGEINFO,
  __module__ = 'exchange_tether_pb2'
  # @@protoc_insertion_point(class_scope:forge_abi.TetherExchangeInfo)
  ))
_sym_db.RegisterMessage(TetherExchangeInfo)

ExchangeTetherTx = _reflection.GeneratedProtocolMessageType('ExchangeTetherTx', (_message.Message,), dict(
  DESCRIPTOR = _EXCHANGETETHERTX,
  __module__ = 'exchange_tether_pb2'
  # @@protoc_insertion_point(class_scope:forge_abi.ExchangeTetherTx)
  ))
_sym_db.RegisterMessage(ExchangeTetherTx)


# @@protoc_insertion_point(module_scope)
