# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: withdraw_token.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import type_pb2 as type__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='withdraw_token.proto',
  package='forge_abi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14withdraw_token.proto\x12\tforge_abi\x1a\ntype.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x01\n\x0fWithdrawTokenTx\x12!\n\x05value\x18\x01 \x01(\x0b\x32\x12.forge_abi.BigUint\x12\n\n\x02to\x18\x02 \x01(\t\x12\x12\n\nchain_type\x18\x03 \x01(\t\x12\x10\n\x08\x63hain_id\x18\x04 \x01(\t\x12\'\n\x03ttl\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')
  ,
  dependencies=[type__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_WITHDRAWTOKENTX = _descriptor.Descriptor(
  name='WithdrawTokenTx',
  full_name='forge_abi.WithdrawTokenTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='forge_abi.WithdrawTokenTx.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='forge_abi.WithdrawTokenTx.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain_type', full_name='forge_abi.WithdrawTokenTx.chain_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='forge_abi.WithdrawTokenTx.chain_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='forge_abi.WithdrawTokenTx.ttl', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=224,
)

_WITHDRAWTOKENTX.fields_by_name['value'].message_type = type__pb2._BIGUINT
_WITHDRAWTOKENTX.fields_by_name['ttl'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['WithdrawTokenTx'] = _WITHDRAWTOKENTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WithdrawTokenTx = _reflection.GeneratedProtocolMessageType('WithdrawTokenTx', (_message.Message,), dict(
  DESCRIPTOR = _WITHDRAWTOKENTX,
  __module__ = 'withdraw_token_pb2'
  # @@protoc_insertion_point(class_scope:forge_abi.WithdrawTokenTx)
  ))
_sym_db.RegisterMessage(WithdrawTokenTx)


# @@protoc_insertion_point(module_scope)
